### ISSUE TITLE
Back button while logging in

### ISSUE THREAD

**Issue by DeadStalker69** [KartikDotDev/Speed-Talk#9]
When logging in and a user account is used, the app sends the user to the create-server page. From there, if I want to switch my account before creating a server, I cannot go back.

**Comment by KartikDotDev** [comment]
Fixed, Added a Sign Out button in the create server modal 
![image](https://github.com/KartikDotDev/Speed-Talk/assets/90651659/34e83a3b-6e70-4dab-8425-918e24277c37)
![image](https://github.com/KartikDotDev/Speed-Talk/assets/90651659/d96ca78d-b954-4145-817c-b7d6e3ddce80)

Now, one can easily sign out if they signed in using the wrong account.
